apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-rc
  labels:
    app: nginx-app
    type: frontend-task
spec:
  replicas: 3
  # optional
  selector:
    type: frontend-task
  template:
    metadata:
      name: nginx-pod
      labels:
        app: nginx-app
        type: frontend-task
    spec:
      containers:
      - name: nginx-container
        image: nginx:1.14.2
        ports:
        - containerPort: 80
