apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      # The range of valid ports is 30000-32767
      nodePort: 30001
  selector:
    app: nginx-app
